### ISSUE TITLE
Dropdown not working!!!

### ISSUE THREAD

**Issue by jeffersonest** [mdbootstrap/Angular-Bootstrap-with-Material-Design#100]
The dropdown appears normally, but the menu is not. Some similar components also do not work, what can be? I followed all the installation steps, it's as if JS was not started! I have a big project built with MDB, I need help regarding this urgent!

**Comment by jeffersonest** [comment]
Now, i'm using 
1 - "https://mdbootstrap.com/download/mdb-angular/ng-free/mdb-angular-free-6.3.0.zip"
2 - imports in app.module.ts = "DropdownModule"

And still not working.

**Comment by jeffersonest** [comment]
app.module.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent } from './app.component';

import {DropdownModule, MDBBootstrapModule} from 'angular-bootstrap-md';
import { FormsModule } from '@angular/forms';
import {DropdownsComponent} from '../../projects/mdb-demo/src/app/components/components/dropdowns/dropdowns.component';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MDBBootstrapModule.forRoot(),
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [ NO_ERRORS_SCHEMA ]
})
export class AppModule { }



app.component.html


<div class="btn-group">

  
  <button class="btn btn-primary dropdown-toggle mr-4" type="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Basic dropdown</button>

  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
  

  
  <div class="dropdown">

    
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Material dropdown</button>


    
    <div class="dropdown-menu dropdown-primary">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
  
</div>

**Comment by Bloodcast69** [comment]
@jeffersonest 

Could you please provide me with the code which produces you those problems? Without it, I won't be able to help you well.

Best Regards,
Damian

**Comment by eLPe21** [comment]
I'm having the very same problem. 
Just downloaded the angular version of MDB , and then 
1. npm install inside the folder.
2. put that into the app.component.html:
`<div class="btn-group">

  
  <button class="btn btn-primary dropdown-toggle mr-4" type="button" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">Basic dropdown</button>

  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
  

  
  <div class="dropdown">

    
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">Material dropdown</button>


    
    <div class="dropdown-menu dropdown-primary">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
  
</div>`

3. ng serve

So the page is styled by MDB however the javascript does not seems to be working and I struggle to find the information how to fix it.
