### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ArjitAgrawal** [mdbootstrap/Angular-Bootstrap-with-Material-Design#101]
### Expected behavior
It should run as usual.
### Actual behavior
It's not running.
### Your working environment and MDB version information
Windows 10, Using angular free 7
### Resources (screenshots, code snippets etc.)
as soon as running "npm start" command, it's showing errors.
![1](https://user-images.githubusercontent.com/33932487/49442292-a3195b00-f7fb-11e8-8bb6-7816c0ad5857.PNG)

**Comment by shikhir-arora** [comment]
Run `npm cache clean` then `npm install -ddd node-sass > npm.log 2> npm.err` — after, make sure you are using version 4.9+ if you’re using Node 10 and 4.10+ if you’re using Node 11. `npm ls node-sass` will list your installed node-sass version.
