### ISSUE TITLE
MDB not supported in angular universal (SSR)

### ISSUE THREAD

**Issue by xxyyzz2050** [mdbootstrap/Angular-Bootstrap-with-Material-Design#103]
ReferenceError: window is not defined

**Comment by idzark** [comment]
Please use our Angular Universal guide and let us know if you encounter any further problems.

https://mdbootstrap.com/docs/angular/getting-started/angular-universal/

**Comment by xxyyzz2050** [comment]
@idzark 
I'm already using Angular universal and tested it, it works very well. but the problem comes when I add MDBBootstrapModule.forRoot() to imports in src/app/app.module.ts

it causes ReferenceError: window is not defined

**Comment by idzark** [comment]
Did you follow our Angular Universal guide? It's hard to tell where exactly is the problem without seeing more code.
