### ISSUE TITLE
Drop Down not working

### ISSUE THREAD

**Issue by eLPe21** [mdbootstrap/Angular-Bootstrap-with-Material-Design#104]
I'm having the very same problem as described here:
https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/issues/100

Just downloaded the angular version of MDB  then 
1. npm install inside the folder.
2. put that into the app.component.html:
Looks wrong here on github -> copied 1st code-example from: https://mdbootstrap.com/docs/jquery/components/dropdowns/

`<div class="btn-group">

  
  <button class="btn btn-primary dropdown-toggle mr-4" type="button" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">Basic dropdown</button>

  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
  

  
  <div class="dropdown">

    
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">Material dropdown</button>

    
    <div class="dropdown-menu dropdown-primary">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
  
</div>`

3. ng serve

So the page is styled by MDB however the dropdown on the button does not work and I struggle to find the information how to fix it. 
collapsed navbar also can't be expanded. 

It all looks like some javascript is not added but the Quick Start video does not mention anything about it.

**Comment by Bloodcast69** [comment]
Dear @eLPe21 

Please note, that you're using jQuery code instead of Angular one. It will never work.

Please use the Angular dropdowns, and everything will be okay.

https://mdbootstrap.com/docs/angular/components/dropdowns/

Best Regards,
Damian
