### ISSUE TITLE
mdbTableSort [sortBy] with capital letters is broken

### ISSUE THREAD

**Issue by mattwebbio** [mdbootstrap/Angular-Bootstrap-with-Material-Design#109]
### Expected behavior
When sorting a table by a column, if the requested attribute has a capital letter (e.g. 'realName' instead of 'realname'), the table should sort by this attribute when the column header is clicked.

### Actual behavior
No sorting is performed.

### Your working environment and MDB version information
Angular 7
angular-bootstrap-md 7.4.3

### Screenshot
![grabacion de pantalla 2019-03-03 a las 7 57 23 a m](https://user-images.githubusercontent.com/420820/53697865-9f5d8c00-3d8a-11e9-9b8d-8573a728762d.gif)

**Comment by Bloodcast69** [comment]
@mattwebbio 

Thanks for your report. 

Before I merge your changes, could you please provide me the code on which I'll be able to reproduce the problem with sorting? 

I have tried to reproduce it, but without success - in every case, I'm able to sort the table (lowercase heading and lowercase data, lowercase heading and uppercase data, uppercase heading and uppercase data, uppercase heading and lowercase data).

**Comment by mattwebbio** [comment]
Hi @Bloodcast69! Thanks for getting back to me - sorry for not leaving you with a clear example.

I've imported some code from our current working environment into a brand new Angular project and pushed it here: https://github.com/mattwebbio/mdbootstrap-broken-sort

**Comment by Bloodcast69** [comment]
Okay, thanks. Now I see where's the problem. We'll test your solution, and if it won't break anything, I'll merge it!

**Comment by Bloodcast69** [comment]
@mattwebbio Your problem will be resolved with MDB Angular 7.4.4.

**Comment by mattwebbio** [comment]
Hi @Bloodcast69, I've just upgraded to 7.4.4 and am still experiencing this issue. Did this fix get delayed?

**Comment by Bloodcast69** [comment]
Hi @mattwebbio, the fix for this situation was shipped with 7.4.4. I have tested it on your application, and there wasn't this problem no more.

Please check one more time, if you're having installed 7.4.4 or 7.4.3.

Please remove the node_modules directory and package-lock.json file, and execute npm install one more time (be sure, that in package.json file you're having angular-bootstrap-md in 7.4.4 version).

**Comment by mattwebbio** [comment]
Hi @Bloodcast69, thanks for getting back to me again. I just performed a fresh clone of the repo I shared above and followed your instructions but it doesn't seem to be working. The `package.json` in the repo is definitely updated to version 7.4.4 (see repo).

Repo: https://github.com/mattwebbio/mdbootstrap-broken-sort/
Live demo (compiled with 7.4.4): https://dev.webb.pw/broken-sort/

Sorry for all the trouble!

**Comment by Bloodcast69** [comment]
@mattwebbio Are you sure, that your server is running with the latest build of application? On the server, it is not working (both in Firefox and Chrome).

I have cloned your repo and run npm install there, and for me, on Firefox it's working fine, but on Chrome, it isn't. On which browser you're trying to run this?

We have definitely fix it for Chrome.

**Comment by mattwebbio** [comment]
Whoops, I built after I updated but not before I followed your instructions and deleted my node_modules/package-lock.json. It may have used the previous version.

I did not test in Firefox, only Chrome. Interesting that it works in one but not the other.

Thank you so much for looking into this!

**Comment by Bloodcast69** [comment]
I'll let you know when this problem will be resolved, but not sooner than Monday, the 15th of April.

**Comment by Bloodcast69** [comment]
@mattwebbio This problem will be definitely resolved with the next release.
