### ISSUE TITLE
@import 'bootstrap/functions' does not exist

### ISSUE THREAD

**Issue by HyenaCros** [mdbootstrap/Angular-Bootstrap-with-Material-Design#11]
mdb.scss tries to import 'bootstrap/functions' but the folder does not exist as of 4.2.0

**Comment by timhaak** [comment]
Oddly the file is in the repo?

**Comment by Gamroth** [comment]
Fixed

**Comment by timhaak** [comment]
Could you possibly bump the version?

**Comment by Gamroth** [comment]
Is bumped to 4.2.1 which fix error with bootstrap/function import

**Comment by timhaak** [comment]
Thanks :)

**Comment by timhaak** [comment]
The package.json still has 4.2.0

**Comment by Gamroth** [comment]
Thanks for the information. Fixed
