### ISSUE TITLE
corousel is overriding vertical scroll behaviour in mobile devices

### ISSUE THREAD

**Issue by justsumant** [mdbootstrap/Angular-Bootstrap-with-Material-Design#113]
when implemented with MDB corousel, the corousel behaviour is as expected, but should also allow vertical scrolling up on corousel.

when dragged vertically up on corousel, it prevents UI from sliding up/down.
angular-bootstrap-md -7.5.1

**Comment by Bloodcast69** [comment]
@justsumant 

You have to add config of HammerJS to your application to allow scrolling vertically on mobile while touching carousel.

Please take a look at our [Mobile](https://mdbootstrap.com/docs/angular/advanced/mobile/#usage) documentation page.
