### ISSUE TITLE
Basic Modal Sample documentation

### ISSUE THREAD

**Issue by urielzen** [mdbootstrap/Angular-Bootstrap-with-Material-Design#114]
ng-uikit-pro-standard-7.4.4

I am trying to follow the example in the following link to create a modal
https://mdbootstrap.com/docs/angular/modals/basic/

Everything seemed to be working fine, I could see the modal showing on button interaction. But when I get to the part "Inject data to the modal"...... the data is not being passed.

I fixed the problem as I was typing my question. The documentation shows to pass the modalOptions like this:

`this.modalRef = this.modalService.show(ModalComponent, { this.modalOptions });`

but for me it worked only passing it like this

`this.modalRef = this.modalService.show(ModalComponent, this.modalOptions);
`

**Comment by Bloodcast69** [comment]
@urielzen 

When you're passing options to the modalService in a flat way (without any variable) you should use the first way:

`this.modalRef = this.modalService.show(ModalComponent, { backdrop: true });`

But if you're having a variable which contains your options, you should pass it as the second example:

```
const modalOptions = { backdrop: true};
this.modalRef = this.modalService.show(ModalComponent, modalOptions); 
```

**Comment by Bloodcast69** [comment]
`this.modalRef = this.modalService.show(ModalComponent, { backdrop: true });`

**Comment by urielzen** [comment]
Thanks for your answer, I understand what you are saying, I just wanted to point out that the documentation incorrectly showing:

![image](https://user-images.githubusercontent.com/7947179/58399628-6433c780-801e-11e9-8c24-edc7ea528d2d.png)
