### ISSUE TITLE
the mdbtable.getdatasource is empty

### ISSUE THREAD

**Issue by mikewakawski** [mdbootstrap/Angular-Bootstrap-with-Material-Design#115]
I wanted to create a table that has a list of users called from my backend using a Spring REST API and I found your project which looked really nice so I followed the inctructions in this tutorial but nothing shows up and even when i do console.log i get an empty list [https://mdbootstrap.com/docs/angular/tables/datatables/]

**Comment by Bloodcast69** [comment]
@mikewakawski 

Please provide me with the code from your app - from the frontend, and how your data on backend looks like.

Without it, I'm unable to help you well.
