### ISSUE TITLE
File to import not found or unreadable: ./angular/mdb-angular-free. (Version 4.3.0)

### ISSUE THREAD

**Issue by timhaak** [mdbootstrap/Angular-Bootstrap-with-Material-Design#12]
Version 4.3.0

File to import not found or unreadable: ./angular/mdb-angular-free.
Parent style sheet: stdin
      in /Users/timhaak/Dev/momentum/TechMaturity/node_modules/angular-bootstrap-md/scss/mdb.scss

**Comment by Gamroth** [comment]
Hi, 

thanks for the info, we will fix it

**Comment by EdByrnee** [comment]
I am also having the same issue, is there a quickfix?

**Comment by EdByrnee** [comment]
I changed

@import "./angular/mdb-angular-free";

to 

@import "./angular/mdb-angular";

at
./node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss

and now the app is compiling :)

**Comment by Gamroth** [comment]
Fixed

**Comment by timhaak** [comment]
Thanks :).

Really like the product.
