### ISSUE TITLE
Cannot find module '@angular/core/src/metadata/lifecycle_hooks

### ISSUE THREAD

**Issue by amrohit** [mdbootstrap/Angular-Bootstrap-with-Material-Design#120]
I am using MD Boostrap with Angular 8. As soon as I ran ng server. It started throwing below error.  
Note: I am not using Pro version. 

ERROR in node_modules/angular-bootstrap-md/lib/navbars/links.component.d.ts(3,31): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.
    node_modules/angular-bootstrap-md/lib/navbars/navlinks.component.d.ts(3,31): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.

**Comment by mdbootstrap** [comment]
@amrohit 

MDB Angular is not ready to use with Angular 8, so if it's possible, please use the Angular 7. 

We'll have to upgrade our MDB Angular to be compatible with Angular 8.

**Comment by kostenickj** [comment]
Will angular 8 support be coming soon?

**Comment by nathbailey** [comment]
If you need to use the package urgently then you can modify line 2 of those files to as below and remove line 3.

`import { AfterContentInit, AfterViewInit, ElementRef, QueryList, EventEmitter } from '@angular/core';`

**Comment by mdbootstrap** [comment]
We'll take a look at this problem soon, and we'll fix it. But the full compatibility of Angular 8 won't be shipped now.

**Comment by zdenekmikel** [comment]
> We'll take a look at this problem soon, and we'll fix it. But the full compatibility of Angular 8 won't be shipped now.

I fixed this issue and is merged, just release a new version.

**Comment by tidusjar** [comment]
What is the ETA for the release? 

I'm hoping soon, this is currently preventing me from upgrading, and I don't really want to drop your library.

**Comment by thefersan** [comment]
> If you need to use the package urgently then you can modify line 2 of those files to as below and remove line 3.
> 
> `import { AfterContentInit, AfterViewInit, ElementRef, QueryList, EventEmitter } from '@angular/core';`

@nathbailey Is this line to be modified in which file? In the error file in question?

**Comment by nathbailey** [comment]
@thefersan the two files which require modifying are:
- node_modules/angular-bootstrap-md/lib/navbars/links.component.d.ts
- node_modules/angular-bootstrap-md/lib/navbars/navlinks.component.d.ts

Remove line 3 and change line 2 to the code above

**Comment by Bloodcast69** [comment]
@tidusjar Are you sure, that you have to update your project to the Angular 8 so soon? We don't want to lose you from using our library.

I'm not able to give you guys some ETA for this, but as far as I can tell, it's two to three weeks. But please, Don't take this term for granted, because a lot of things can affect him.

**Comment by HarryAlvarado28** [comment]
@amrohit @nathbailey @thefersan What I did temporarily was, comment on the lines and erase the class.

![Temporal](https://user-images.githubusercontent.com/15837452/59226478-b0434800-8b98-11e9-87e4-44f6693e14e5.png)

![Compiled successfully](https://user-images.githubusercontent.com/15837452/59226589-f8fb0100-8b98-11e9-95bf-fa3ec506f0ca.png)


## :warning: Attention, this is not the best solution. :warning:

**Comment by tidusjar** [comment]
@Bloodcast69 any update?

**Comment by Bloodcast69** [comment]
We're getting closer. MDB Angular 8 will be shipped on the next Monday.

**Comment by kathygit** [comment]
Is it released ? It is Monday July 8th.

**Comment by Bloodcast69** [comment]
@kathygit Yes, MDB 8 is live.
