### ISSUE TITLE
Package configuration issue

### ISSUE THREAD

**Issue by jayotirana** [mdbootstrap/Angular-Bootstrap-with-Material-Design#127]
### Expected behavior
It should work according to the details that are mentioned for angular.json in the npm package i.e https://www.npmjs.com/package/angular-bootstrap-md
### Actual behavior
It's not working and giving error for the path that are mentioned under angular.json for styles.
### Your working environment and MDB version information
angular 8 and mdb version is 8.1.1
### Reference used:
"node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss",
    "node_modules/angular-bootstrap-md/scss/mdb-free.scss",

### Fixed required:
"node_modules/angular-bootstrap-md/assets/scss/bootstrap/bootstrap.scss",
              "node_modules/angular-bootstrap-md/assets/scss/mdb.scss",

from scss to assets/scss and mdb-free.scss to mdb.scss
For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by idzark** [comment]
Fixed.
