### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by rui-cruz** [mdbootstrap/Angular-Bootstrap-with-Material-Design#14]
Hi,

I can't get it to work.. It seems that webpack.config.js is ignoring all scss's, because if I add 
>@import "../node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss";
to my styles.scss the some css styles are applyed..

Is this due to be the free version?

I'm testing on a electron seed project, you can [use it](https://github.com/maximegris/angular-electron) to try and check if you have same issue.

Thank you,
Rui

**Comment by rui-cruz** [comment]
No support? How will I consider paying if no one help me?

At this moment, I've tried material2, material-web-components and angular2-mdl, and I need to choose one to start my project. I would want to try this one before trowing the towel..

I have this error:
>ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader!./node_modules/sass-loader/lib/loader.js?{"includePaths":["node_modules"]}!./src/styles.scss
Module not found: Error: Can't resolve '../font/roboto/Roboto-Thin.eot' in 'C:\Users\infor\Desktop\test-app\src'
 @ ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader!./node_modules/sass-loader/lib/loader.js?{"includePaths":["node_modules"]}!./src/styles.scss 6:111365-111406 6:111429-111470
 @ ./src/styles.scss
 @ multi styles.scss

this error goes on and on for all fonts and svg's/png's


I'm using webpack 3.3.0, I added "includePaths" option to sass-loader like this:

{
        "include": [
          path.join(process.cwd(), "src/styles.scss")
        ],
        "test": /\.scss$|\.sass$/,
        "loaders": ExtractTextPlugin.extract({
          "use": [
            "css-loader?{\"sourceMap\":false,\"importLoaders\":1}",
            "postcss-loader",
            {
              loader: "sass-loader",
              options: {
                includePaths: ['node_modules']
              }
            }
          ],
          "fallback": "style-loader",
          "publicPath": ""
        })
      },


Could you just please update doc's for webpack 3, or have a sample app with webpack 3 or help me out on this?

**Comment by mdbootstrap** [comment]
Hi rui-cruz.

Your problem was caused by npm, not github package itself. However, we've fixed this issue. Try installing our package via npm again (npm i angular-bootstrap-md).

Best Regards.

**Comment by mdbootstrap** [comment]
Hi rui-cruz.

Thanks for reporting this issue. It has been just fixed, try installing our package via npm again,

Best Regards.
