### ISSUE TITLE
Can not find the module 'angular-bootstrap-md'

### ISSUE THREAD

**Issue by efgonz** [mdbootstrap/Angular-Bootstrap-with-Material-Design#15]
After install it via npm and import it on a new project created with @angular/cli: 1.4.0
instalation is complete but can not find the module.

import { MDBBootstrapModule } from 'angular-bootstrap-md';

Can not find the module 'angular-bootstrap-md'

**Comment by efgonz** [comment]
A a workaround I imported from:

import { MDBBootstrapModule } from 'angular-bootstrap-md/src/app/typescripts/free';

**Comment by abductedMind** [comment]
For some reason they removed the index file from the root of the package. this is breaking it for me as well. I downgraded to version 4.3.1 and that fixed the problem

**Comment by mdbootstrap** [comment]
Hi efgonz.

Your problem was caused by npm, not github package itself. However, we've fixed this issue. Try installing our package via npm again (npm i angular-bootstrap-md).

Best Regards.

**Comment by mdbootstrap** [comment]
Hi everyone.

This issue has been fixed. Try installing package via npm again.

Best Regards.
