### ISSUE TITLE
angular-bootstrap-md not working with webpack

### ISSUE THREAD

**Issue by akadtn** [mdbootstrap/Angular-Bootstrap-with-Material-Design#19]
I'm installed angular-bootstrap-md using your instructions via npm.

The following error apears:
  
ERROR in ./~/angular-bootstrap-md/index.ts
Module parse failed: ..\angular-bootstrap-md\index.ts Unexpected character '@' (78:0)
You may need an appropriate loader to handle this file type.

How this problem can be fixed? Does anyone knows what should i do?

**Comment by qasdf123** [comment]
Hi, how did you solve this?
