### ISSUE TITLE
Can Not Find Index.js

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [mdbootstrap/Angular-Bootstrap-with-Material-Design#25]
I'm getting the following error:

Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\XXX\Documents\OTC\OTC\node_modules\angular-bootstrap-md\index.js'

Any idea on how I can resolve this? I think there's supposed to be an index.js in the node_module for this npm package. I'm using Ionic.

**Comment by mdbootstrap** [comment]
Dear @TimeTravelersHackedMe , 

are you sure that:
-the file exists in the following location? 
-there is no space in the path (not sure whether XXX is a real location or obfuscated value)
-the user used for building/compiling has access right to the file. 

Also please provide us more information about your environment (os, Angular/Angular CLI version, Typescript)

**Comment by TimeTravelersHackedMe** [comment]
Hey @mdbootstrap ,

The problem is that when including the project with a Typescript import, it looks for index.js. This file does not exist in the mdboostrap project. There is only a index.ts file.

When I look at other modules that successfully import, the projects include .js files as well.

**Comment by TimeTravelersHackedMe** [comment]
I'm using the latest version of Ionic on Windows

**Comment by TimeTravelersHackedMe** [comment]
Ionic CLI 3.18.0 and ionic-angular 3.8.0 and Angular 4.4.4

**Comment by mdbootstrap** [comment]
Check this #23

**Comment by TimeTravelersHackedMe** [comment]
@mdbootstrap  What does that have to do with my question? It's a different error.

**Comment by mdbootstrap** [comment]
This library is not compiled by default to js, if you would like to use it you have to use index.ts therefore you should add path to index.ts to your compiler. The easiest way would be to use npm install. Within next releases we are planning to switch to js.
