### ISSUE TITLE
Followed Quick Start instructions trying to use chip/badge missing but "chip" scss styles are missing from source

### ISSUE THREAD

**Issue by jimbarrett33** [mdbootstrap/Angular-Bootstrap-with-Material-Design#30]
Following the Quick Start instructions I was trying to test out the chip/badge component but it seems like the chip scss styles are missing from src.

**Comment by mdbootstrap** [comment]
Dear @jimbarrett33 , 
Chips are available in MDB PRO (see MDB PRO COMPONENT label next to it). You can find more information about that here: 
https://mdbootstrap.com/product/angular-bootstrap-pro/
