### ISSUE TITLE
Angular input label not working correctly

### ISSUE THREAD

**Issue by Vienyame** [mdbootstrap/Angular-Bootstrap-with-Material-Design#33]
On input focus or when typing value, label doesn't move up.

```
<div class="md-form">
        <input type="text" id="defaultForm-email" class="form-control" mdbActive>
        <label for="defaultForm-email">Your email</label>
    </div>
```

**Comment by mdbootstrap** [comment]
Dear Vienyae, 
unfortunately I cannot reproduce your issue.  I've just checked it on the fresh copy and it works like a charm. Please make sure that you have followed getting started correctly.

**Comment by DanielNetzer** [comment]
I can confirm that this bug still exists, copied the input from the doc's into a fresh mdb project installed from NPM and followed the entire Get Started guide and labels are not working.

**Comment by stich6269** [comment]
faced with the same thing
