### ISSUE TITLE
error path src of image 

### ISSUE THREAD

**Issue by Thanhtung351992** [mdbootstrap/Angular-Bootstrap-with-Material-Design#34]
![screenshot from 2017-12-01 11-41-43](https://user-images.githubusercontent.com/34156270/33475743-1872f2ba-d6b2-11e7-8545-6bcc0b93f2f5.png)
![screenshot from 2017-12-01 11-54-11](https://user-images.githubusercontent.com/34156270/33475763-280c27dc-d6b2-11e7-931e-8083623341b2.png)

I use path relative for url image but when run project that error as photo above. Who can help me ?

**Comment by mdbootstrap** [comment]
That depends on your .angular-cli.json file, by default folder assets is exposed:

>       "assets": [
>         "assets",
>         "favicon.ico"
>       ],

therefore if you place your image here: /assets/images/image.jpg, you will be able to link it as below:

`<img src="/assets/images/image.jpg">
`
