### ISSUE TITLE
Impossible to overwrite the "$image-path" variable

### ISSUE THREAD

**Issue by PositronBeam** [mdbootstrap/Angular-Bootstrap-with-Material-Design#36]
The file scss/mdb/free/data/_variables.scss should contain a "!default" for this variable, so we would be able to overwrite it with angular-cli.
Line 135: 
// Images Path
$image-path: '../img/' !default;

For example, in my project, I need to overwrite this variable with "$image-path: '~angular-bootstrap-md/img';" and I have to modify the file in "node_modules".

**Comment by mdbootstrap** [comment]
#37

**Comment by Kurshith** [comment]
Issue still exist with latest version.
