### ISSUE TITLE
ERROR in ./node_modules/angular-bootstrap-md/index.ts

### ISSUE THREAD

**Issue by kashish-walkwel** [mdbootstrap/Angular-Bootstrap-with-Material-Design#38]
ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: /home/kashish/walkwel/passwordmanager/node_modules/angular-bootstrap-md/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/home/kashish/walkwel/passwordmanager/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (/home/kashish/walkwel/passwordmanager/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 11:29-60
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by mdbootstrap** [comment]
Duplicate https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/issues/23

**Comment by kashish-walkwel** [comment]
i have tried to use both solutions but still i am facing the same issue.

**Comment by Hava-Layosh** [comment]
me too.
Any Solution?

**Comment by Bloodcast69** [comment]
@Hava-Layosh 

Provide me more information about your environment. 

I need to know your angular-bootstrap-md version, Angular version, OS. Also please paste me here code of your tsconfig.json file.

Also, it would help me, if you could send me your project at d.gemza@mdbootstrap.com with information, from which ticket comes message.
