### ISSUE TITLE
Error loading MDB module

### ISSUE THREAD

**Issue by edyrkaj** [mdbootstrap/Angular-Bootstrap-with-Material-Design#39]
Uncaught Error: Can't resolve all parameters for ComponentLoaderFactory: (?, ?, ?, ?, ?)

**Comment by Bloodcast69** [comment]
Hello edyrkaj,
Could you provide me more informations about your's problem? Your's configuration, angular-cli etc.. I can't guess what's wrong without it :) 

Best Regards,
Damian

**Comment by mdbootstrap** [comment]
Dear @edyrkaj please provide us with additional information, otherwise, we will close the ticket due to lack of response.
