### ISSUE TITLE
Input type=number label not working

### ISSUE THREAD

**Issue by littledan45** [mdbootstrap/Angular-Bootstrap-with-Material-Design#4]
When having a `<input type="number">` the label class="active" does not get activated.

```
<form [formGroup]="testForm" (ngSubmit)="onSubmit()">
  <div class="md-form">
    <input mdbActive
      type="number"
      id="age_id"
      formControlName="age_id"
      class="form-control">
    <label for="age_id">Age</label>
  </div>
</form>
```

**Comment by EDabrowskaRamm** [comment]
Hello,

Thank you for noticing this! It will be fixed in next releases.

**Comment by AdrianSaw** [comment]
Temporary fix (until released) : https://mdbootstrap.com/forums/topic/angular-input-label-not-working-correctly/

**Comment by AdrianSaw** [comment]
fixed and will be added in closest release
