### ISSUE TITLE
Type 'null' is not assignable to type 'ElementRef'

### ISSUE THREAD

**Issue by MrAndersonDG** [mdbootstrap/Angular-Bootstrap-with-Material-Design#43]
https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/blob/98554b6fb582005eb12c95750f13907392a1e244/src/carousel/carousel.component.ts#L26

[ts] Type 'null' is not assignable to type 'ElementRef'

**Comment by MrAndersonDG** [comment]
ERROR in [at-loader] ./node_modules/angular-bootstrap-md/carousel/carousel.component.ts:26:3
        TS2322: Type 'null' is not assignable to type 'ElementRef'.

    ERROR in [at-loader] ./node_modules/angular-bootstrap-md/carousel/carousel.component.ts:112:8
        TS2322: Type 'undefined' is not assignable to type 'number'.

**Comment by Bloodcast69** [comment]
Hello MrAndersonDG, please could you provide me more informations about your's environment, configuration of your's angular, which version etc? I've checked this component yesterday, and it works well.

Best Regards,
Damian

**Comment by thirumanidev** [comment]
Hi,
What's the solution for this issue?
This is my Angular & Typescript version.
![image](https://user-images.githubusercontent.com/55808656/113513224-39a1e680-9586-11eb-864d-d333cd94f6e5.png)

`@ViewChildren("stakeRef") myValue: QueryList<ElementRef> = null;`
If I use the above code an error occurs as below
**_Type 'null' is not assignable to type 'QueryList<ElementRef<any>>'_**

How to initialize values for different datatypes?
