### ISSUE TITLE
Modal BackDrop unable to subscribe

### ISSUE THREAD

**Issue by Max-Lev** [mdbootstrap/Angular-Bootstrap-with-Material-Design#48]
Hi, 

how is possible to subscribe to backdrop hide/hidden event?

**Comment by mdbootstrap** [comment]
Dear @Max-Lev could you please explain why do you want to subscribe to backdrop instead of modal? Please check API reference : https://mdbootstrap.com/angular/advanced/modals/#advancedUsage

**Comment by mdbootstrap** [comment]
Closing due to lack of input data from user
