### ISSUE TITLE
webpack and tslint false positive warnings

### ISSUE THREAD

**Issue by surenrao** [mdbootstrap/Angular-Bootstrap-with-Material-Design#50]
[tsconfig.txt](https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/files/1689940/tsconfig.txt)
[tslint.txt](https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/files/1689941/tslint.txt)

I am getting lot of warnings similar to below
`WARNING in ./node_modules/angular-bootstrap-md/carousel/carousel.component.ts
[13, 13]: The selector of the component "CarouselComponent" should have prefix "my" (https://angul
ar.io/styleguide#style-02-07)`
Looks like my projects tslint.json is being used for angular-bootstrap-md code?
what can i do to fix this? (no other lib does this, first time seeing such issue)

**Comment by Bloodcast69** [comment]
Dear surenrao,
You could try to edit tslint.json file. In directive-selector and component-selector, change my, to app.
And when you generate new components, selector for it will be for example app-second for secondComponent.
Or without editing tslint.json, please check if your's components got my- prefix in selectors.
For example:
second.component.ts file:
selector: 'my-second',

Best Regards,
Damian

**Comment by surenrao** [comment]
Sorry for the confusion, but i already have proper prefixes on components. 
tslint is expecting 'my' prefix on your library's component. 
For example your component at /node_modules/angular-bootstrap-md/carousel/carousel.component.ts already has 'mdb' prefix. but for some reason tslint expects it to be 'my'.

**Comment by Bloodcast69** [comment]
Dear Surenrao,
could you provide me reproduction steps? I can't reproduce your's case.
Best Regards,
Damian

**Comment by Bloodcast69** [comment]
Dear Surenrao, please answer my question or I close your ticket due to lack of response.
Best Regards,
Damian
