### ISSUE TITLE
git repo code failed to compile 

### ISSUE THREAD

**Issue by Gokula2010** [mdbootstrap/Angular-Bootstrap-with-Material-Design#53]
I just clone the code from git repo. I follow thru the steps, 

1. git clone https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design.git .
2. npm i
3. npm start

But, My npm start get failed. please see the below error,

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/mdb-free.scss
Module build failed:
@import "./angular/mdb-angular";
^
      File to import not found or unreadable: ./angular/mdb-angular.
Parent style sheet: stdin
      in C:\Gokula\Study\Development\AngularJS\ng5-mdbs-01\src\scss\mdb-free.scss (line 64, column 1)
Error:
@import "./angular/mdb-angular";
^
      File to import not found or unreadable: ./angular/mdb-angular.
Parent style sheet: stdin
      in C:\Gokula\Study\Development\AngularJS\ng5-mdbs-01\src\scss\mdb-free.scss (line 64, column 1)
    at options.error (C:\Gokula\Study\Development\AngularJS\ng5-mdbs-01\node_modules\node-sass\lib\index.js:291:26)
 @ ./src/scss/mdb-free.scss 4:14-202
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/bootstrap/bootstrap.scss ./src/scss/mdb-free.scss ./demo/src/styles.scss
ERROR in src/index.ts(1,31): error TS2307: Cannot find module 'ng-mdb-pro/free/inputs/deep.directive'.

webpack: Failed to compile.

**Comment by mdbootstrap** [comment]
Fixed with https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/commit/5e55d8cfc615fd87d8413e11deac11dd042d2e60

**Comment by Gokula2010** [comment]
thank you for your updated, however, after fix, i got new issue, "Cannot find module 'ng-mdb-pro/free/inputs/deep.directive'."

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-13T01:54:55.132Z
Hash: c95162073e2b3d7a367b
Time: 9366ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.96 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 655 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.4 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 854 kB [initial] [rendered]

ERROR in src/index.ts(1,31): error TS2307: Cannot find module 'ng-mdb-pro/free/inputs/deep.directive'.


webpack: Failed to compile.

**Comment by mdbootstrap** [comment]
Dear @Gokula2010 , this also has been fixed in: https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/commit/58a3772fa2547a50eb8f31e36731c831b6070da4 . Please pull the new project
