### ISSUE TITLE
text input control's label get overlapped

### ISSUE THREAD

**Issue by Gokula2010** [mdbootstrap/Angular-Bootstrap-with-Material-Design#54]
Hi, I follow thru the steps "How to install MDB via npm:" from README.md and tried to add a new md-form and single input box ( i grab the code from inputs demo).

demo site working as expected 
![image](https://user-images.githubusercontent.com/11747759/36130218-7d5ae722-10a6-11e8-8026-889f5f9a7fff.png)

but when I tried the same code, input control's label gets overlapping. see the below,

![image](https://user-images.githubusercontent.com/11747759/36130134-07976df8-10a6-11e8-929b-a5f52840cc47.png)

**Comment by Bloodcast69** [comment]
Hello @Gokula2010 
It's looks like that you're using code from our jquery version.
Please refer to our Angular documentation:  https://mdbootstrap.com/angular/components/inputs/
If problem will still exists, please let me know.
Best Regards,
Damian

**Comment by Gokula2010** [comment]
Sorry, Damian.

Yes, I copied the wrong example. Example with Angular is working. Thanks

**Comment by Bloodcast69** [comment]
Glad that everything is working fine.
Closing topic.
Best Regards,
Damian
