### ISSUE TITLE
Please, see my issue: "Can't find module: angular-bootstrap-md/index (@5.2.0) #277", running in stackblitz

### ISSUE THREAD

**Issue by mcristiano** [mdbootstrap/Angular-Bootstrap-with-Material-Design#56]
Can't find module: angular-bootstrap-md/index (@5.2.0) #277

I'm using stackblitz to study
[https://github.com/stackblitz/core/issues/277](url)

See my project!

[https://stackblitz.com/edit/my-mdbootstrap-study](url)

**Comment by mdbootstrap** [comment]
Please try to run project locally, and make sure to follow installation steps, especially: 

- add following into tsconfig.json file located in root folder
> "include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],

**Comment by mcristiano** [comment]
First of all, thank you for returning so quickly!

Unfortunately the stackblitz environment does not yet allow customizing tsconfig, so I'll have to use another environment to train and learn,

again thanks for the return and congratulations to all by MDBOOSTRAP it is beautiful and useful in both worlds bootstrap and material design

**Comment by mdbootstrap** [comment]
Dear @mcristiano , please try using your local environment - here you can find step-by-step tutorial for  all operating systems (Windows, macOS, Unix) on how to use MDB Angular on your local machine: https://mdbootstrap.com/angular/angular-environment-installation/

**Comment by mcristiano** [comment]
Locally works perfect but would like to use a cloudide to keep study projects easy to access and up to date without having to set the environment!

Thank you anyway, I'm trying the codesandbox.io now ... but for now, it's the same problem!

Anything I'll use the dropbox;)

**Comment by mdbootstrap** [comment]
Dear @mcristiano , we will be shipping JS versions in a future. Once that happens you will be able to use it in cloud runtime environments.
