### ISSUE TITLE
NPM does not create free folder

### ISSUE THREAD

**Issue by HyenaCros** [mdbootstrap/Angular-Bootstrap-with-Material-Design#6]
I tried installing angular-bootstrap-md on a fresh angular project and I'm receiving a 'File to import not found or unreadable' error for 'mdb/free/data/prefixer'. When I checked inside node_modules/angular-bootstrap-md/scss/mdb there was no 'free' subfolder, the contents were directly inside the mdb folder.

**Comment by Gamroth** [comment]
At this moment create their this folder, we will fix it in closest release

**Comment by Gamroth** [comment]
Fixed!
