### ISSUE TITLE
Collapsed Icon Wrong on Angular

### ISSUE THREAD

**Issue by wwiatt** [mdbootstrap/Angular-Bootstrap-with-Material-Design#60]
Using the angular template code mentioned [here](https://mdbootstrap.com/angular/layout/navigation/).  When the screen is collapsed the icon includes an fa fa-bars span inside of the normal collapsed icon.  I have included the required packages mentioned in the documentation as well.

Removing `<i class="fa fa-bars"></i>` from navbar.component.html made this go away. It looks like the navbar-toggler-icon is the intended icon and for some reason the fa-bars icon was embedded in the same span.

<img width="374" alt="funkybar" src="https://user-images.githubusercontent.com/3474033/36771156-ac471084-1c1c-11e8-83a6-6b92ae4e8280.png">

**Comment by Bloodcast69** [comment]
Hello wwiatt,
Yes we know about this problem. It will be fixed in today's release.
Best Regards,
Damian
