### ISSUE TITLE
Collapse error

### ISSUE THREAD

**Issue by BunyodUz** [mdbootstrap/Angular-Bootstrap-with-Material-Design#65]
When I'm trying use this:

```
<button class="btn btn-primary waves-light" type="button" (click)="test.toggle()" mdbRippleRadius>
    Toggle collapse
</button>

<div class="" [mdbCollapse]="isCollapsed" #test="bs-collapse">
    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
</div>
```

I'm getting this error:

> Error: Template parse errors:
> Can't bind to 'mdbCollapse' since it isn't a known property of 'div'.

(I imported modules)

**Comment by Bloodcast69** [comment]
Dear BunnyodUz,
Please add NO_ERRORS_SCHEMA to your app.module.ts. It should help you.
Best Regards,
Damian

**Comment by BunyodUz** [comment]
Thanks bro! It works.
But i didn't understand why do need `isCollapsed` property. Its property is not changing when collapsed.

**Comment by Bloodcast69** [comment]
BunyodUz, it's caused by this, that isCollapsed property is used in structure of collapse. We're working on solving this case.
Best Regards,
Damian
