### ISSUE TITLE
Not able to override the $image-path sass viable 

### ISSUE THREAD

**Issue by Kurshith** [mdbootstrap/Angular-Bootstrap-with-Material-Design#67]
The file scss/mdb/free/data/_variables.scss should contain a "!default" for this variable, so we would be able to overwrite it with angular-cli.
Line 135:
// Images Path
$image-path: '../img/' !default;

For example, in my project, I need to overwrite this variable with "$image-path: '~angular-bootstrap-md/img';" and I have to modify the file in "node_modules".

**Comment by Bloodcast69** [comment]
Dear @Kurshith thanks for your report! We'll take look at this, and we'll fix this in our next release.
Best Regards,
Damian
