### ISSUE TITLE
angular2-google-maps should be removed from the package

### ISSUE THREAD

**Issue by IvanFarkas** [mdbootstrap/Angular-Bootstrap-with-Material-Design#7]
angular2-google-maps should be removed from the package since it has an npm package.
angular2-google-maps has a new version with breaking changes.
Old name: angular2-google-maps
New NPM pkg name: **@agm/core**

**Comment by AdrianSaw** [comment]
Thanks for your suggestion. We're adding it to our list and we will change it with the closest release.

**Comment by AdrianSaw** [comment]
Removed
