### ISSUE TITLE
Modal is throwing: "cannot read property of undefined"

### ISSUE THREAD

**Issue by hsoto92** [mdbootstrap/Angular-Bootstrap-with-Material-Design#70]
So I have my modal html here: 

```
<div mdbModal #subscriptionModal="mdb-modal" id="ClientSubscriptionModel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog cascading-modal" role="document">
        <div class="modal-content">
            <div class="modal-header light-blue darken-3 white-text">
                <h4 class="title"><i class="fa fa-newspaper-o"></i> Subscription form</h4>
                <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close" (click)="form.hide()">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body mb-0">
                <div class="md-form form-sm">
                    <i class="fa fa-lock prefix"></i>
                    <input mdbActive type="password" id="form27" class="form-control">
                    <label for="form27">Your name</label>
                </div>
                <div class="md-form form-sm">
                    <i class="fa fa-envelope prefix"></i>
                    <input mdbActive type="text" id="form28" class="form-control">
                    <label for="form28">Your email</label>
                </div>
                <div class="text-center mt-1-half">
                    <button class="btn btn-info mb-1 waves-light" mdbRippleRadius>Submit <i class="fa fa-check ml-1"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
```
This is the button that calls it:

```
<button type="button" class="btn btn-primary waves-light" mdbRippleRadius
(click)="subscriptionModal.show()" data-toggle="modal" data-target="#ClientSubscriptionModel">
    Más Información
</button>
```

And here's my subscription-modal.component.ts:

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'subscription-modal',
  templateUrl: './subscription-modal.component.html',
  styleUrls: ['./subscription-modal.component.scss']
})
export class SubscriptionModalComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```

Here, I'm importing the component to app.module.ts:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { MDBBootstrapModule } from 'angular-bootstrap-md';


import { AppComponent } from './app.component';
import { NavbarComponent } from './navbar/navbar.component';
import { CtaclientComponentComponent } from './ctaclient-component/ctaclient-component.component';
import { SubscriptionModalComponent } from './subscription-modal/subscription-modal.component';


@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    CtaclientComponentComponent,
    SubscriptionModalComponent
  ],
  imports: [
    BrowserModule,
    MDBBootstrapModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [ NO_ERRORS_SCHEMA ]
})

export class AppModule { }

```

And finally, inside my app.component.html file I have this:

```
<header>
        <landing-navbar></landing-navbar>
        <div ctaclient-component></div>
</header>

<subscription-modal></subscription-modal>
```

When I click the button to Open the modal, it throws an error on the console:

```
ERROR TypeError: Cannot read property 'show' of undefined
    at Object.eval [as handleEvent] (CtaclientComponentComponent.html:20)
    at handleEvent (core.js:13547)
    at callWithDebugContext (core.js:15056)
    at Object.debugHandleEvent [as handleEvent] (core.js:14643)
    at dispatchEvent (core.js:9962)
    at eval (core.js:10587)
    at HTMLButtonElement.eval (platform-browser.js:2628)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
```
Anything wrong that I'm doing that is not shown on the docs?

**Comment by Bloodcast69** [comment]
Dear @hsoto92 I've tried to reproduce your case, but for me, everything is working just fine. Could you tell me, if you're getting this error when you're using modal in your app-component? Without using other components?
Best Regards,
Damian

**Comment by hsoto92** [comment]
Damian, hello! Indeed, when I copy and paste the code of the modal inside the same component with the button that calls the modal, it works just fine, however that's not how I would like it to work since I want to have a specific component for the actual modal and a seperate component for the call to action item that calls the modal. 

Is there a fix for this?

**Comment by hsoto92** [comment]
It is throwing the following error: 

`[Angular] Identifier 'subscriptionModal' is not defined. The component declaration, template variable declarations, and element references do not contain such a member`

Apparently, if the modal is in another component and I call it from a different component it throws that error. How can I fix it?

**Comment by Bloodcast69** [comment]
Do you import this component in your appmodule ? 
There's something wrong with your component. Please check those links for answer:
https://stackoverflow.com/questions/48992824/the-component-declaration-template-variable-declarations-and-element-reference
https://github.com/angular/vscode-ng-language-service/issues/81

Best Regards,
Damian

**Comment by hsoto92** [comment]
Here's the app itself. Please check the ctaclient-component.component.html, it throws the error I mention. 
[sampleapp.zip](https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/files/1846895/sampleapp.zip)

**Comment by Bloodcast69** [comment]
Dear hsoto92, It won't work in this way because content from subscription-modal component is not visible in ctaclient component. You have to add code from subscription-modal below your modal button in ctaclient component.
Best Regards,
Damian

**Comment by hsoto92** [comment]
Ok Damian I understand, however, what's the point of making an angular based UX framework if you can't actually work the way it's suppose to be?

You should be able to have the component approach on your framework otherwise you're breaking the SOLID principle Angular respects so much to begin with.

**Comment by SerhiDi** [comment]
Write 'modal' code inside 'wrapper' component it is not Angular way.

**Comment by SerhiDi** [comment]
Can you create methods like in Angular Material?:
[Angular dialog](https://material.angular.io/components/dialog/examples)
