### ISSUE TITLE
Module not found: Error: Can't resolve '../img//svg/arrow_right.svg'

### ISSUE THREAD

**Issue by amirensit** [mdbootstrap/Angular-Bootstrap-with-Material-Design#72]
I am facing this error when I use this line :
`@import "../node_modules/angular-bootstrap-md/scss/mdb-free.scss",`

neither this worked : 
`@import "~angular-bootstrap-md/scss/mdb-free.scss";   `
I am using scss

**Comment by Bloodcast69** [comment]
Dear @amirensit in which situation you're getting this error? Which component are you using? 
Also please provide me your environment informations (Angular version, typescript, node, npm, os, browser).
Best Regards,
Damian

**Comment by amirensit** [comment]
I fixes the  probem using this link.

https://mdbootstrap.com/support/mdb-with-jhipster/
