### ISSUE TITLE
waves effect doesn't work

### ISSUE THREAD

**Issue by premnathj** [mdbootstrap/Angular-Bootstrap-with-Material-Design#73]
Hi,
I followed the tutorial from here https://mdbootstrap.com/getting-started/5min-quickstart/
No errors but the waves effect doesn't work. 

Please help me what could be wrong?

Thanks,
Prem

**Comment by Bloodcast69** [comment]
Dear @premnathj as we've said in our changelog, mdbRippleRadius is now deprecated. If you're using MDB Angular 6, please use mdbWavesEffect directive. If this won't work, let me know.
Best Regards,
Damian

**Comment by premnathj** [comment]
Thanks @Bloodcast69 . Now Waves effect do work. 
But I am finding tough time to make the dropdown work in the NavBar. Basically, The dropdown is displayed with very light color and when I click the dropdown nothing gets displayed.
 BTW, I am using the Angular version. PFB my environment details.
`
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.10",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@angular/platform-server": "^5.2.10",
    "@angular/router": "^5.2.10",
    "angular-bootstrap-md": "^6.0.0",
    "chart.js": "^2.5.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8", `

**Comment by Bloodcast69** [comment]
Could you show me some screenshots or sample code?

**Comment by premnathj** [comment]
PFA the screen shot and below is the code.


<mdb-navbar SideClass="navbar fixed-top navbar-expand-md navbar-dark indigo"
>

<logo><a class="navbar-brand" href="#">Nav Bar</a></logo>

<links>

<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<a class="nav-link waves-light" mdbWavesEffect>Home<span class="sr-only">
(current)</span></a>
</li>
<li class="nav-item">
<a class="nav-link waves-light" mdbWavesEffect>Link Welder</a>
</li>

<li class="nav-item dropdown btn-group" dropdown>
<a dropdownToggle type="button" class="nav-link dropdown-toggle waves-light"
mdbWavesEffect>
Basic dropdown<span class="caret"></span></a>
<div *dropdownMenu class="dropdown-menu dropdown dropdown-primary" role=
"menu">
<a class="dropdown-item waves-light" href="#" mdbWavesEffect>Action</a>
<a class="dropdown-item waves-light" href="#" mdbWavesEffect>Another action
</a>
<a class="dropdown-item waves-light" href="#" mdbWavesEffect>Something else
here</a>
<div class="divider dropdown-divider"></div>
<a class="dropdown-item waves-light" href="#" mdbWavesEffect>Separated link
</a>
</div>
</li>
</ul>

</links>

</mdb-navbar>

**Comment by premnathj** [comment]
![screen shot 2018-04-18 at 5 12 36 pm](https://user-images.githubusercontent.com/17021049/38996387-16b02c08-43b9-11e8-9c52-01801d278203.png)

**Comment by Bloodcast69** [comment]
Dear @premnathj please download one more time repo from Github. These problems are fixed now.
Best Regards,
Damian

**Comment by premnathj** [comment]
Hi Damian,

Thanks a lot for the quick fix.
Just curious in which version of the package it broke?

Regards,
Prem

**Comment by premnathj** [comment]
Hi Damian,

dropdown-menu-right doesn't work on the dropdownMenu. I have a dropdown at the right most end of the Nav Bar and I would like to do "dropdown-menu-right". But looks like it doesn't recognize. Could you please check from your side?

Thanks,
Prem

**Comment by Bloodcast69** [comment]
Dear premnathj,
Please describe me which behavior do you expect, and which behavior occurs now. Provide me some code or screenshots.
Thanks,
Damian

**Comment by dawidadach** [comment]
Closing issue due to lack if input.  @premnathj  if you can provide us with any additional details, feel free to reopen the issue.
