### ISSUE TITLE
Input validation potential bug

### ISSUE THREAD

**Issue by premnathj** [mdbootstrap/Angular-Bootstrap-with-Material-Design#74]
Hi,

In the below example, When we just type one word then its working as expected. But when we type 2 words separated by a space, it shows the "data-error" text instead of "data-success" text.

<form [formGroup]="validatingForm">
    <div class="md-form">
        <input mdbInputDirective type="text" id="form1" class="form-control" data-error="Something went wrong..." data-success="Everything is okay!" formControlName="required">
        <label for="form1">Required validator</label>
    </div>
</form>
   
Please check and let me know at the earliest.

Thanks

**Comment by premnathj** [comment]
Also even for if the single word contains any specials character then its displaying "data-error"

**Comment by Bloodcast69** [comment]
Dear premnathj, 
Which type of input you're using? mdbInputDirective validates inputs through their type. 
text type allows you to put everything from A-za-z0-9.
Best Regards,
Damian

**Comment by premnathj** [comment]
Hi Damian,

My TS file:

```
  this.groupForm = this.fb.group({
        name: [null, Validators.required]
    });

```

My HTML:
```
<form [formGroup]="groupForm">
                  <div class="md-form">
                      <input mdbInputDirective type="text" id="form1" class="form-control" data-error="Something went wrong..." data-success="Everything is okay!" formControlName="name">
                      <label for="form1">Required validator</label>
                  </div>
              </form>
```
When I enter a single work with only alphanumeric then it shows success.
If I enter other than non-alpha numeric then it shows error.
This is just a required field validation and it should just validate if there is any text or not. And not for any special characters.

In your site example, it works fine (as expected). Attached the screen shot.
<img width="1100" alt="screen shot 2018-04-23 at 9 52 03 am" src="https://user-images.githubusercontent.com/17021049/39130876-2b72dd0e-46dc-11e8-98b7-1f34db1e9a96.png">

But it doesn't work in my code.
I am using Angula: 5.2.10
and "angular-bootstrap-md": "^6.0.1",

Thanks,
Prem

**Comment by Bloodcast69** [comment]
Dear @premnathj,
It's working correctly. Your data-error and data-success attributes show validation not from Angular's required Validator, but from mdbInputDirective validation.

mdbInputDirective validates through the type of your input. Text input validation from mdbInputDirective allows putting everything except special signs like (%, ^, #, -, +) or white signs.

If you don't want to use validation from mdbInputDirective (there are only a few basic examples), please add [mdbValidate]="false" control to your input. 

In your example you're missing error message. Please check again Required Validators in our docs:
https://mdbootstrap.com/angular/forms/input-validation/#required

Best Regards,
Damian

**Comment by dawidadach** [comment]
Closing issue due to lack if input. @premnathj   if you can provide us with any additional details, feel free to reopen the issue.
