### ISSUE TITLE
Template parse errors when following Angular getting started + Full Page Intro with fixed Navbar

### ISSUE THREAD

**Issue by herwert** [mdbootstrap/Angular-Bootstrap-with-Material-Design#75]
When following the Angular getting started 5 min tutorial. Then I copy the example: Full Page Intro with fixed Navbar. I get parse errors below. Can you please help out?

Parse Error:
Can't bind to 'containerInside' since it isn't a known property of 'mdb-navbar'.
1. If 'mdb-navbar' is an Angular component and it has 'containerInside' input, then verify that it is part of this module.
2. If 'mdb-navbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("r SideClass="navbar fixed-top navbar-expand-lg navbar-dark indigo scrolling-navbar intro-fixed-nav" [ERROR ->][containerInside]="false">
      <logo>
          <a class="logo navbar-brand" href="#"><strong>Navba"): ng:///AppModule/AppComponent.html@1:112
'logo' is not a known element:
1. If 'logo' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("bar-expand-lg navbar-dark indigo scrolling-navbar intro-fixed-nav" [containerInside]="false">
      [ERROR ->]<logo>
          <a class="logo navbar-brand" href="#"><strong>Navbar</strong></a>
      </logo>
"): ng:///AppModule/AppComponent.html@2:6
'links' is not a known element:
1. If 'links' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <a class="logo navbar-brand" href="#"><strong>Navbar</strong></a>
      </logo>
      [ERROR ->]<links>
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active waves-ligh"): ng:///AppModule/AppComponent.html@5:6
'mdb-navbar' is not a known element:
1. If 'mdb-navbar' is an Angular component, then verify that it is part of this module.
2. If 'mdb-navbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<header>

Angular CLI: 1.7.4
Node: 9.8.0
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

My app.module.ts looks like:
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { MDBBootstrapModule } from 'angular-bootstrap-md';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    MDBBootstrapModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [ NO_ERRORS_SCHEMA ]
})
export class AppModule { }

**Comment by Bloodcast69** [comment]
@herwert Which version of MDB Angular you're using? I've used example code: https://mdbootstrap.com/angular/layout/navigation/#i-f-n with 6.0.1 version, and for me, everything is working fine.
Best Regards,
Damian

**Comment by dawidadach** [comment]
Dear @herwert could you update your answer with version? Otherwise, ticket will be closed due to lack of information to reproduce.
