### ISSUE TITLE
Character counter doesn't work

### ISSUE THREAD

**Issue by premnathj** [mdbootstrap/Angular-Bootstrap-with-Material-Design#76]
Hi,
Here are the steps to reproduce the issue:

- Go to https://mdbootstrap.com/angular/angular-bootstrap-getting-started/ and use the "Direct download" button to download the project.
- Extract the zip file and do the "npm install" inside the project.
- Do "npm start". The project will be up and running at http://localhost:4200
- Open the app.component.html and paste the below code. This code its taken from taken from this https://mdbootstrap.com/angular/forms/inputs/
```
<div class="md-form">        
    <textarea class="md-textarea form-control " rows="3" id="input_text" type="text" length="120" mdbCharCounter mdbInputDirective></textarea>
    <label for="input_text">Type your text</label>
</div> 
```
- Save the changes. The UI will be refreshed and the newly added textarea box will be visible.
- Type "Some Test Text"
Expect result:  The character count should be displayed at the bottom right corner of the textarea control.
- Actual result: No count info is getting displayed.

We are planning to buy "Pro" version but I am worried why do even the basics things are not working.
Requesting your attention at the earliest.

Thanks,
Prem

**Comment by premnathj** [comment]
Hi,
Please let me know if you have any updates on this.
Thanks,
Prem

**Comment by dawidadach** [comment]
Dear @premnathj , character count is a Premium component available in PRO version, therefore it doesn't work with free package. I've just tested it with fresh PRO copy and it works like a charm :)

**Comment by dawidadach** [comment]
@premnathj , yes we will fix it soon , thank you.
