### ISSUE TITLE
unknown compiler option 'include' for angular 6

### ISSUE THREAD

**Issue by bhavsarradhe** [mdbootstrap/Angular-Bootstrap-with-Material-Design#79]
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Bloodcast69** [comment]
Dear @bhavsarradhe Could you provide me more informations about your problem? What exactly doesn't work to you?
