### ISSUE TITLE
Edit installation instructions to cover change in ng6

### ISSUE THREAD

**Issue by challamzinniagroup** [mdbootstrap/Angular-Bootstrap-with-Material-Design#81]
The installation instructions (via npm) indicate how to edit the `angular-cli.json` file to change the `css` extension to `scss`.

This is different for projects created from the cli as of Angular 6.
The file is now called `angular.json` (they have omitted the `-cli`.
The edit is different. It now should be:
```
"schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
```

It would be helpful to have your instructions updated to demonstrate both versions.

Thanks!

**Comment by Bloodcast69** [comment]
Thanks! We'll change this.

**Comment by challamzinniagroup** [comment]
Good morning, thanks for the quick reply. Is there a specific npm command required to install the Angular 6 version?
Upon running the command as instructed, and shown below, I get the following output:
```
$ npm i angular-bootstrap-md --save
npm WARN angular-bootstrap-md@6.1.1 requires a peer of @angular/core@^5.0.0 but                                       none is installed. You must install peer dependencies yourself.
npm WARN angular-bootstrap-md@6.1.1 requires a peer of @angular/common@^5.0.0 bu                                      t none is installed. You must install peer dependencies yourself.
npm WARN angular-bootstrap-md@6.1.1 requires a peer of @angular/http@^5.0.0 but                                       none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse                                      vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                      1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                      )
```

I have all of these modules already as this is on a brand new project created from the AngularCLI (v6.0.7) with Angular (v6.0.3).

It seems from the output from the command that perhaps the default npm install is still the v5x?

Can you offer any insight or clarification please?

Thanks!

**Comment by challamzinniagroup** [comment]
@Bloodcast69 
Adding (once again) to my previous comment - the source here appears to be fully ng6.0 ready. I'm wondering now if perhaps the npm has not been updated to match? I will pull the repo and try to get it running from there. :)

**Comment by Bloodcast69** [comment]
@challamzinniagroup those warnings are described in our FAQ:
https://mdbootstrap.com/angular/faq/
Best Regards,
Damian

**Comment by challamzinniagroup** [comment]
@Bloodcast69 Thank you for pointing me to this - I had not seen it previously! :)
