### ISSUE TITLE
Angular Admin Dashboard free v1  - Hamburger Menu not working

### ISSUE THREAD

**Issue by zulihan** [mdbootstrap/Angular-Bootstrap-with-Material-Design#82]
Hi,
I've got an issue with the burger menu. 
It doesn't toggle the menu.
And it doesn't work on your site neither : [http://ng-admin.mdbootstrap.com/dashboards/v1](url)

### Expected behavior
Clicking on the burger menu should toggle the navigation.

### Actual behavior
Clicking on the button doesn't do anything. No errors in the console.

### Your working environment and MDB version information
I've unzipped the free Admin dahsboard, installed the packages (npm install), installed the rxjs-compat.
Everything's working fine for now except the burger menu and the pagination.
I haven't touched the code. No modification of your code.

### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

How can I fix this ?

Thanks for your help

**Comment by idzark** [comment]
Hi,

Thank you for reporting the problem. We will fix this in next release.
