### ISSUE TITLE
6.2.0 bloats by 500 KB compared to 6.1.6

### ISSUE THREAD

**Issue by Stardraw** [mdbootstrap/Angular-Bootstrap-with-Material-Design#86]
### Expected behavior
No significant increase in built code
### Actual behavior
Output size increased by 500KB
### Your working environment and MDB version information
Angular CLI: 6.0.8
Node: 10.1.0
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

Before: angular-bootstrap-md@6.1.6
chunk {scripts} scripts.js (scripts) 22.7 kB  [rendered]
chunk {0} runtime.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.css (styles) 75.7 kB [initial] [rendered]
chunk {2} polyfills.js (polyfills) 98.2 kB [initial] [rendered]
chunk {3} main.js (main) 1.53 MB [initial] [rendered]

After: angular-bootstrap-md@6.2.0
chunk {scripts} scripts.js (scripts) 22.7 kB  [rendered]
chunk {0} runtime.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.css (styles) 75.7 kB [initial] [rendered]
chunk {2} polyfills.js (polyfills) 98.2 kB [initial] [rendered]
chunk {3} main.js (main) 2.02 MB [initial] [rendered]

### Resources (screenshots, code snippets etc.)
I suspect it may have to do with the fact that chart.js is now a required package and is not a dependency.
When I initially updated, I could not build:
ERROR in ./node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js
Module not found: Error: Can't resolve 'chart.js' in 'c:\Stardraw\sdo2\node_modules\angular-bootstrap-md\esm5'
ERROR in chunk main [initial]
[name].js
c:\Stardraw\sdo2\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js??ref--17-0!c:\Stardraw\sdo2\node_modules\@ngtools\webpack\src\index.js!c:\Stardraw\sdo2\src\main.ts eb82ee2210fc092975280de215baf3ce
Unexpected token (3086:19)
|             options: options
|         };
|         return new !(function webpackMissingModule() { var e = new Error("Cannot find module \"chart.js\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())(ctx, opts);
|     };
|     /**

I had to manually install chart.js - even though I don't use it.
It then built ok but increased main.js from 1.53MB to 2.02MB
Of course, this is my own project but all that was changed was the version number of mdbootstrap.

**Comment by Stardraw** [comment]
Of course, the 3rd solution is to stay on 6.1.6 until this problem is fixed in 6.2.1
I also don't want to build my own js files as I want to continue developing in Typescript and let the angular-cli/webpack do the tree shaking for me.
I am considering purchasing the pro version but only if an obvious regression is fixed in a reasonable amount of time.

**Comment by Bloodcast69** [comment]
@Stardraw 
This problem won't be fixed with 6.2.1 because it's the valid behavior.

For people who don't want to use Charts and they need to optimize their apps, we have prepared a package with the possibility to compile library at their own. 

So if you don't need something from our library just recompile that package which you want to use.

**Comment by Stardraw** [comment]
This is not the valid behaviour. Angular supports Tree Shaking. If you include a component and don't reference it, it will not get included in the compiled output.
Also, if mdbootstrap requires chart.js, it should include it and have it as a dependency. This is a breaking change since 6.1.6
I should be able to import the modules I need and only the modules that are used should be included in the final output.
This is the great thing about Angular - you no longer have to deal with 3rd party js files anymore as the compiler will include just what is used.
If you are saying that it is valid behaviour to include unused modules and that I should manually remove those bogus references from your code myself and generate my own js files and that I will have to do this every time you update your code then I will have to seriously reconsider using your components as I still see no valid reason or benefit why this changed for 6.2.0

**Comment by Local9** [comment]
Have not tried this but, correct me if I'm wrong this error wouldn't show if;

1. The chart module is the only piece that looks for chart.js and not the base libary
2. If using the base module MDBBootstrapModule.forRoot() it would pull in the charts module, therefore requires chart.js
3. If not using the charts module and then only including the modules which are required and not the MDBBootstrapModule.forRoot() it should not show this error

That is if the chart module is the only thing that requires chart.js

I agree that a dependancy that is not required should also not be included to "make it work" but really should be contained within the chart module and only required if using that module.

Am I on the right path here?

**Comment by Stardraw** [comment]
I agree.
If I'm not importing a module that depends on chart.js, then I should not need to add that as a dependency.
I am only importing the carousel module and yet it forces me to install chart.js and then appears to include it in the generated javascript which explains the bloated code.

**Comment by Bloodcast69** [comment]
Guys,

This problem should be resolved with the MDB Angular 7.4.0

Best Regards,
Damian

**Comment by Stardraw** [comment]
I reported this problem 7 months ago and said "I am considering purchasing the pro version but only if an obvious regression is fixed in a reasonable amount of time.". I was then told "This problem won't be fixed with 6.2.1 because it's the valid behavior." to which I replied "This is not the valid behaviour.". Finally, 7 months later, it is fixed. I am glad I did not pay for a pro version and eventually found another Angular library with better support. You need to listen to your customers when they report a problem.
