### ISSUE TITLE
Error importing SCSS file 

### ISSUE THREAD

**Issue by riyadali** [mdbootstrap/Angular-Bootstrap-with-Material-Design#88]
### Expected behavior
Import to work
### Actual behavior
I'm importing the scss file for mdbootstrap_angular in my styles.scss file.  The actual stmt used is 
@import "~angular-bootstrap-md/scss/mdb-free";

I'm getting an error in the _forms.scss file
### Your working environment and MDB version information
I'm using stackblitz and version 6.0.2 of angular-bootstrap-md

### Resources (screenshots, code snippets etc.)

The actual received is as follows

Error in angular-bootstrap-md/scss/free/_forms.scss (5:3)
property "input" must be followed by a ':'

When I looked up this file in your repository at https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/
this is what I see in this file (and indeed on line 5 you have  input[type=text] ).

// Forms basic
// Input + label wrapper styles
.md-form {
  // Text inputs
  input[type=text],
  input[type=password],
  input[type=email],
  input[type=url],
...

So is the syntax above correct for an scss file.  Am I missing some helper function that may be embedded out of order.

This is what I have in my index.html file
link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" 
         integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  
 Add bootstrap social library for social media icons -->
link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css" rel="stylesheet"> 

 Add font awesome icon library -->
link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
   

A workaround could be if I included the styles for mdbootstrap-angular directly in my index.html as references.  But I can seem to find a .css file for angular-bootstrap-md at the 6.2.0 level.  I tried this approach using the link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet"
but it doesn't appear to be the correct level.  In particular the dropdown button in the toolbar does not work (which I reported in a different issue which has been closed).

Thanks and regards.

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Bloodcast69** [comment]
@riyadali Could you try to check if this problem exists with the latest 6.2.1 version of MDB Angular?

**Comment by riyadali** [comment]
Sorry it took so long to respond.  But I just tried this at the 6.2.2 level of angular-bootstrap-md and still getting 

Error in angular-bootstrap-md/scss/free/_forms.scss (5:3) property "input" must be followed by a ':'

**Comment by riyadali** [comment]
Note: as previously mentioned: this was imported in my styles.scss file using
@import "~angular-bootstrap-md/scss/mdb-free.scss";

**Comment by Bloodcast69** [comment]
@riyadali Could you please provide me a reproduction repository on which I'll be able to debug your problem?

**Comment by riyadali** [comment]
Use this link https://stackblitz.com/github/riyadali/townofbabylon/tree/test

I imported the bootstrap scss files as follows (no issues with this import)

@import "~angular-bootstrap-md/scss/bootstrap/bootstrap.scss";

In the styles.scss file I then also have an import for mdb-free as follows

@import "~angular-bootstrap-md/scss/mdb-free.scss";

This causes the error message.  The site loads but obviously the
mdbootstrap styling is not applied.

You can see what it should look like by uncommenting out the css reference
to mdbootstrap in the index.html file as shown below
(question for you -- what is the equivalent link reference for
mdb-free.scss?)



Thanks for your help

**Comment by Bloodcast69** [comment]
@riyadali I want to download your project, so please paste me a link to your github repository of something similar.

**Comment by riyadali** [comment]
Here's the link to the "test" branch of the "TownOfBabylon" repository.

https://github.com/riyadali/TownOfBabylon/tree/test

**Comment by Bloodcast69** [comment]
@riyadali 
Could you please provide me the steps with which I'll be able to debug your problem using your test repository?

**Comment by Bloodcast69** [comment]
@riyadali where in Stackblitz project folder structure is node_modules directory, or where you have installed a angular-bootstrap-md package? I need to locate this package installed in your project.

**Comment by riyadali** [comment]
Stackblitz installs dependencies on the fly since it is hosted in the
cloud.  Under Stackblitz the reference to the node modules folder is as
follows
"~angular-bootstrap-md/scss/bootstrap/bootstrap.scss"

The tilde has special meaning. So this basically translates to

"node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss"

Thanks again
Riyad

**Comment by Bloodcast69** [comment]
Dear @riyadali 

I have run your project on my local computer instead of Stackblitz, commented out src/styles.scss imports (because they are unnecessary), and I have fixed styles paths in angular.json file (instead of ~angular-bootstrap-md it should be node_modules/angular-bootstrap-md), and everything is working fine.

The styles are working fine.
Maybe the problem is in your imports on Stackblitz? (try to change ~ to node_modules/), and try one more time.

Best Regards,
Damian

**Comment by riyadali** [comment]
Hello,

Thanks.  You can close this problem out.  It may be a Stackblitz issue.
Just for your information the node_modules/angular... reference does not
work with Stackblitz.  It only works with the ~angular... reference.

In any case, thanks for your help.

Riyad

**Comment by FaisalMushtaaq** [comment]
found out that md5 is only working with scss. Migrated my project to SCCS, problem solved
