### ISSUE TITLE
Collapse error when building

### ISSUE THREAD

**Issue by isamely** [mdbootstrap/Angular-Bootstrap-with-Material-Design#90]
When I run ng build --prod --verbose the terminal gives me this error: 
ERROR in src\app\arma-presupuesto\seleccion-producto\seleccion-producto.component.html(58,31): : Property 'isCollapsed' does not exist on type 'SeleccionProductoComponent'.

In seleccion-producto.component.ts there are these lines:

`import { Component, OnInit, ViewChild, Input, Output, EventEmitter } from '@angular/core';
import { CollapseDirective } from 'angular-bootstrap-md';

export class SeleccionProductoComponent implements OnInit {

    @ViewChild('test') public test: CollapseDirective;
}`

what is wrong with the code?

**Comment by Bloodcast69** [comment]
Dear isamely,
In 6.2.3 release the CollapseDirective was changed to CollapseComponent. So change it in your code, and everything will be working fine.
Best Regards,
Damian
