### ISSUE TITLE
Navbar Wraps to new line 

### ISSUE THREAD

**Issue by riyadali** [mdbootstrap/Angular-Bootstrap-with-Material-Design#91]
### Expected behavior
Navbar to stay on one line and some items to align to the right

### Actual behavior
It appears that anything that follows the /ul for the group of links flows to a new line.  For example I had an inline search form and that pulled to the right. I also tried it with having a grouping of font-awesome flex-icons instead of search form and that also flowed to a new line instead of pulling to the right.

So in example below, I have two lines with the Navbar brand centered vertically between the two lines and then Home, Features, Pricing and Options left aligned on the top line with the facebook, instagram and twitter icons on the second line and also left aligned.  I am surprised that it is not honoring the mr-auto bootstrap class on the ul (ul class="navbar-nav mr-auto"), which you think would cause the social icons to be placed on the far right of the line.  Instead it appears that the /ul pushes the icons to a new line.

In my experimentation when I move the social icons ul group (or for that matter the inline search form) before /ul ending the very first ul group, I get everything to stay on one line but the social icons are not pulled to the right.  How do I get it to stay on a single line, with my social icons aligned to the right.

### Your working environment and MDB version information
angular-bootstrap-md 6.2.3
bootstrap 4.1.3

### Resources (screenshots, code snippets etc.)
Below is the code sample which causes multiple lines from link (https://mdbootstrap.com/angular/layout/navigation/)

```<mdb-navbar SideClass="navbar fixed-top navbar-expand-lg navbar-dark pink scrolling-navbar ie-nav" [containerInside]="false">
    <mdb-navbar-brand>
        <a class="logo navbar-brand" href="#"><strong>Navbar</strong></a>
    </mdb-navbar-brand>
    <links>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active waves-light" mdbWavesEffect>
                <a class="nav-link">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link">Features</a>
            </li>
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link">Pricing</a>
            </li>
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link">Opinions</a>
            </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="nav-item waves-light" mdbWavesEffect>
                <a class="nav-link"><i class="fa fa-instagram"></i></a>
            </li>
        </ul>
    </links>
</mdb-navbar>

**Comment by Bloodcast69** [comment]
Dear @riyadali 
I have tried to reproduce your problem with the code from our documentation but without success. For me, navbar is looking as it should. 
Could you please provide me with some screenshots of actual behavior and the code which you're using in your app instead of this from the docs?

**Comment by riyadali** [comment]
Ok I experimented some more and just attached a vanilla bootstrap 4 navbar
and it worked and everything aligned as it should be.  So I compared it
against the mdbootstrap version.  So the parent container for the ul
elements in the vanilla bootstrap navbar is just a div which is as follows:

div _ngcontent-c1="" class="navbar-collapse collapse" id="navbarNavDropdown"

Critically, it has a style of -- display: flex!important; -- from the
navbar-collapse class.

When I use the mdbootstrap navbar the immediate parent of the ul is the
links element (links _ngcontent-c12="").  And the parent of the links
grouping is the div with the class of nav-bar-collapse.  When I view the
links display attribute, it has a default of display:block.  This then
causes all of its child elements to stack vertically.



I have somewhat of a hack, where I specify a style on the links as follows

links class="myflex"

and then in my scss file I have the following defined

.myflex {
  display: flex:
}

This works and everything now stays on one line.  The problem is that it
does not align the searchbox to the right.  At least I understand the
problem now.  The links tag that is required for mdb-navbar is causing the
problem.

How is it working in your environment.  Perhaps you can tell me what are
the attributes of your links element.  If it has a display of flex where is
it getting it from.

Note, I am using the mdboostrap free angular package.

Regards,
Riyad

**Comment by riyadali** [comment]
One final comment.  To fully fix the problem the width for the links group need to be set to 100% and this is easily accomplished by specify the bootstrap w-100 class on the links tag.  Also to get display of flex I could have used the bootstrap d-flex class.  However, there was still one minor issue to be resolved when the menu was collapsed.  In this case the search bar floats to the right instead of being on a separate line by itself since the display attribute is still set to flex when it should be inline or block when collapsed.  My hack to fix this was to still use my custom myflex class and set the display attribute to inherit and now it works fine both when the navbar is expanded as well as when it is collapsed.  I would have preferred not to use a custom class but I'm no expert at CSS and it works.
