### ISSUE TITLE
Can't resolve 'chart.js'

### ISSUE THREAD

**Issue by ikismail** [mdbootstrap/Angular-Bootstrap-with-Material-Design#92]
### Actual behavior
Got Error after Installing angular-bootstrap-md 
```Module not found: Error: Can't resolve 'chart.js' ```
### Your working environment and MDB version information
I Installed  ```"angular-bootstrap-md": "^6.2.4"```, and got error while running application
My angular version 
```
Angular CLI: 6.2.3
Node: 8.11.1
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
```
### Resources (screenshots, code snippets etc.)
```
ERROR in ./node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js
Module not found: Error: Can't resolve 'chart.js'
```
![alt text](https://image.ibb.co/fQ4MSU/error.png)
For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Bloodcast69** [comment]
@ikismail 
Try to install types for chart.js library, and check if problem is gone or not.
Here's the line which you should type in your application's terminal:
`npm install --save-dev @types/chart.js`

**Comment by ikismail** [comment]
"angular-bootstrap-md": "^6.1.1" working fine without any error

**Comment by Bloodcast69** [comment]
@ikismail could you please provide me with reproduction steps, with which I'll be able to reproduce your problem?

**Comment by ikismail** [comment]
Hi @Bloodcast69 Here Is my environment Settings

* Windows : Windows 10 Pro
* Version : 1803
* OS build : 17134.285
* OS: win32 x64
* Browser : Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
* Angular CLI: 6.2.3
* Node: 8.11.1
* Angular: 6.1.9

I tried to install `angular-bootstrap-md` for my angular application of version `^6.2.4`,
When I run `npm serve` It throws 

`ERROR in ./node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js Module not found: Error: Can't resolve 'chart.js' in 'E:\**ProjectDirectory**\node_modules\angular-bootstrap-md\esm5' i ｢wdm｣: Failed to compile.`

**Comment by idzark** [comment]
Hello @ikismail 
Please install chart.js package and update scripts array in angular.json with: 

"node_modules/chart.js/dist/Chart.js"

**Comment by ambujkhanna** [comment]
This warning still present

> WARNING in ./node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js 6986:53-69
> "export 'defineInjectable' was not found in '@angular/core'

**Comment by Bloodcast69** [comment]
@ambujkhanna 

Could you please try to remove package-lock.json file and node_modules directory, and execute npm install one more time? 

If this won't resolve your problem, could you please provide me with the reproduction repository on which I'll be able to debug your case?

Best Regards,
Damian

**Comment by shardulsonar** [comment]
Getting the same error !

**Comment by Bloodcast69** [comment]
Guys if you want help from me, please show me the code which produces you those errors. 

Without it, I won't be able to help you well.

**Comment by ambujkhanna** [comment]
i didn't write any special code. I just installed and it fires me error in the library.
