### ISSUE TITLE
Bar chart example in the documentation is wrong

### ISSUE THREAD

**Issue by ShinShil** [mdbootstrap/Angular-Bootstrap-with-Material-Design#95]
### Expected behavior
For bar chart example ts code should match.

### Actual behavior
In bar chart section in code in ts I see unknown example, I suggest this is code from line chart example. See screenshot below. Datasets are wrong 100%.

### Your working environment and MDB version information
https://mdbootstrap.com/angular/advanced/charts/#bar-chart

### Resources (screenshots, code snippets etc.)
https://mdbootstrap.com/angular/advanced/charts/#bar-chart

![image](https://user-images.githubusercontent.com/11064696/47602771-038ece80-d9ec-11e8-8400-c9a16a4feb6c.png)

PS. I think that it is good to mention in your documentation that it is need to import ChartsModule for child modules. Actually this is expected behaviour, and I have found the ref in the api section. But it wasn't obvious and it is **not** highlighted. I think it is good to highlight in some way because it is very important note, and for now is easy to miss it.

**Comment by Bloodcast69** [comment]
@ShinShil Thanks for your report! 

Which behavior in your opinion is the best behavior?

Should we add the second dataset to Bar Chart live example, or we should remove the second dataset from TypeScript code?

About the API Reference: Information about how to import our Charts is placed at the bottom of the page, and we won't add some additional informations how to use our charts below the every example.

Best Regards,
Damian

**Comment by ShinShil** [comment]
@Bloodcast69 Thanks for your reply!

There is missmatch not only in the amount of datasets, but also in datasets' labels and values.

I think better **to update the Bar Chart live example**. It will be good to see in the example how bar chart handles case with two datasets.

**Comment by Bloodcast69** [comment]
@ShinShil Thanks for your advice! We'll take care of this case in the future!

Best Regards,
Damian
