### ISSUE TITLE
Input custom validation not working

### ISSUE THREAD

**Issue by SerhiDi** [mdbootstrap/Angular-Bootstrap-with-Material-Design#98]
### Validation not workiing

Angular validation success/error messages show wrong text

 [Documentation for inputs](https://mdbootstrap.com/docs/angular/forms/validation/)

https://gyazo.com/c20a63c8c8465edee79e61639e897d7a

```
<input
  mdbInputDirective
  type="text"
  class="form-control"
  formControlName="firstName"
  [errorMessage]="formErrors.firstName"
  [validateSuccess]="false"
  required>
```

Validation working ONLY if I use `data-error` or `data-success` attributes, with static text

`[errorMessage]` or `[successMessage]` working incorrect.
When I click on input field I have 'wrong' text instead custom message (I need empty message, because  variable `formErrors.firstName` empty in this moment). When I start typing - message correct.
https://gyazo.com/0b4ed38c55d674914e7dae3e802d365f

**Comment by idzark** [comment]
Thank you for letting us know about this problem. It will be fixed in next version.
